---
- name: My First Playbook
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: install package
    package:
      name: httpd
      state: installed

  - name: install telnet
    user:
      name: telnel
      state: installed



  - name: add bob
    user:
      name: bob
      state: present