---
- name: My First Playbook
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: install package
    package:
      name: httpd
      state: installed


  - name: install telnet
    package:
      name: httpd
      state: removed