---
- name: Prom Agent Installation
  hosts: localhost
  become: true
  become_method: sudo
  user: ec2-user
  tasks: 

  - name: Download Node Exporter
    shell: wget https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz

  - name: Extract the Node Exporter
    shell: tar xvfz node_exporter-0.18.1.linux-amd64.tar.gz

# - name: Unarchive a file that needs to be downloaded (added in 2.0)
#   unarchive:
#     src: https://example.com/example.zip
#     dest: /usr/local/bin
#     remote_src: yes

  - name: Create prometheus directory
    file: 
      path: /etc/prometheus
      state: directory
      owner: prometheus
      group: prometheus
   
  - name: Move and Rename Node Exporter
    shell: mv node_exporter-0.18.1.linux-amd64 /etc/prometheus/node_exporter

  - name: Create Service File
    copy:
      src: node_exporter.service
      dest: /etc/systemd/system/

  handlers: 
    name: AGENT_RESTART
    service: 
      name: node_exporter
      state: restarted
      enabled: true
