---
- name: R1soft Agent Installation
  hosts: all
  become: true
  become_method: sudo
  user: centos
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "6")
  tasks: 

  - name: Create Repo
    copy:
      src: r1soft.repo
      dest: /etc/yum.repos.d/


  - name: Install Agent
    package:
      name: serverbackup-enterprise-agent
      state: latest 
   notify: AGENT_RESTART



  - name: Stop Iptables
    service:
      name: iptables
      state: stopped
      enabled: false


  - name: Get Key
    shell: "r1soft-setup --get-key http://backup.gbeksbaby.com/"



  handlers: 
    name: AGENT_RESTART
    service: 
      name: cdp-agent 
      state: restarted
      enabled: true














 