---
- name: Stop Services
  hosts: all #DB
  become: true
  become_method: sudo
  user: centos
  ignore_errors: true #dont stop if there are erros
  tasks: 
  - name: stop rlsoft CentOS 7
    when: (ansible_distribution == "CentOS" and ansible_distribution_version == "7")
    systemd: 
      name: sbm-agent
      state: stopped
    ignore_errors: true

 - name: stop rlsoft on CentOS 6
    when: (ansible_distribution == "CentOS" and ansible_distribution_version == "6")
    service: 
      name: cdp-server
      state: stopped
    ignore_errors: true

  - name: stop filbeat
    when: (ansible_distribution == "CentOS" and ansible_distribution_version == "7")
    systemd: 
      name: filbeat
      state: stopped
    ignore_errors: true
    

    - name: stop NRPE
      when: (ansible_distribution == "CentOS" and ansible_distribution_version == "7")
    systemd: 
      name: nrpe
      state: stopped
    ignore_errors: true


  - name: stop MariaDB
    when: (ansible_distribution == "CentOS" and ansible_distribution_version == "7")
    systemd: 
      name: mariadb
      state: stopped

