---
- name: Install wordpress
  hosts: all
  become: true
  become_method: sudo
  user: centos

  tasks: 
  - name: install webserver  centos
    package: 
      name: httpd
      state: latest
      enabled: true

  - name: Install all packages
    package: 
      name: mysql
      nane: mariadb-server
      name: php
      name: php-mysql
      state: latest

  - name: Download wordpress
    get_url: 
      url: https://wordpress.org/latest.tar.gz
      dest: /tmp/

  - name: Unzip wordpress
    unarchive: 
      src: /tmp/wordpress
      dest: /var/www/html/
      remote_src: yes

  - name: Start webserver
    service: 
      name: httpd
      state: restarted
      enabled: true

  - route53:
       
      state: present
      zone: gbeksbaby.com
      record: wordpress.gbeksbaby.com
      type: A
      ttl: 7200
      value: 1.1.1.1,