---

- name: Install wordpress
  hosts: all
  become: true
  become_method: sudo
  user: centos

  tasks:

    # - name: Download wordpress
    #   when: ansible_os_family == "centos" 
    #   get_url:
    #     url: https://wordpress.org/latest.tar.gz
    #     dest: /tmp/

    # - name: install webserver  Debian
    #   when: ansible_os_family == "Debian"
    #   package:
    #   name: apache2

    - name: install webserver  centos
      when: ansible_os_family == "Centos"
      package:
        name: httpd
        state: latest
        enabled: true

    - name: Install all packages
      package:
        name: "{{ item }}"
      with_items:
        - mysql
        - mariadb-server
        - php
        - php-mysql

    - name: Download wordpress
       get_url: 
         url: https://wordpress.org/latest.tar.gz
         dest: /tmp/

    - name: Unzip wordpress
      unarchive:
        src: /tmp/wordpress
        dest: /var/www/html/
        remote_src: yes

    - name: Start webserver
      service: 
        name: httpd
        state: restarted
        enabled: true

    - route53:
        state: present
        zone: gbeksbaby.com
        record: wordpress.gbeksbaby.com
        type: A
        ttl: 7200
        value: 1.1.1.1,